### ISSUE TITLE
Display liquidation risk level in a graphic with 3 tier colors based on c-ratio. 

### ISSUE THREAD

**Issue by GHesericsu** [jet-lab/jet-v1#241]
Proposed by a discord member. My added comments and idea here. We currently show users a warning when they lower their C-ratio to a level that's subject to liquidation, but the c-ratio color on cockpit is green which looks too comfortable.  Maybe add like a circle scale thing like our utilization rate in assetDetail. They will be able to how much in dollar amount they can potentially borrow to hit certain level or risk depending on their risk tolerance. 

For example, I deposited 10 SOL(~$1500 today). I have already borrowed $750 USD. And I want to see how much $USD left I can still borrow to hit a risk level where I will only get liquidated if SOL drops 20%. And see the big picture without having to mess with max borrow in the input field. 

Another potential way to do this without adding more to the cockpit is to create a modal like assetDetail but for C-ratio or risk level detail. 

When users enter the app first, they're not clear on at what level of c-ratio they will get liquidated by Jet. Jet's max c-ratio should be cleared stated. Maybe in the c-ratio definition if we want to eliminate clutters. 

Risk levels:
Red - critical - deposit or repay immediately
Yellow - high -  Monitor more frequently 
Green - Low or moderate - Good standing 

<img width="242" alt="Screen Shot 2021-10-09 at 11 45 50 PM" src="https://user-images.githubusercontent.com/60202455/136674457-27f80056-a9bb-4934-84a2-570ce0943561.png">

**Comment by holross** [comment]
Really good point, this is important info to be able to interpret quickly for users. I'm going to play around with this, I think it will require a little finagling on my part

**Comment by holross** [comment]
Just a couple of updates since my first post @loganjross. As a rule of thumb, you can refer to Figma file for latest but I'll try to keep screenshots up to date too. 

<img width="483" alt="Screen Shot 2021-10-11 at 2 02 54 PM" src="https://user-images.githubusercontent.com/91745209/136835486-92d443af-14bc-4667-b0ae-d83231abb723.png">
<img width="402" alt="Screen Shot 2021-10-11 at 1 38 47 PM" src="https://user-images.githubusercontent.com/91745209/136835481-e0925996-3ae9-4cf9-aea3-2d9669866dd3.png">
<img width="786" alt="Screen Shot 2021-10-11 at 2 11 15 PM" src="https://user-images.githubusercontent.com/91745209/136835537-d79c1a96-fc4d-468d-b35d-729c04ea1e5a.png">
